apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: hgrinhauz/bitcoin-be:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: DB_HOST
            value: "mysql-service"
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: "root"
          - name: DB_PASSWORD
            value: "rootpassword"
          - name: DB_NAME
            value: "crypto_db"
    ports:
        - containerPort: 5001
