services:
  web:
    build: ./fe
    container_name: frontend
    ports:
      - "5002:5002"
    depends_on:
      - backend-service
    networks:
      - crypto-net

  backend-service:
    build: ./be
    container_name: backend
    ports:
      - "5001:5002"
    depends_on:
      - mysqldb
    environment:
       MYSQL_HOST: mysqldb
       MYSQL_USER: root
       MYSQL_PASSWORD: 123456
    networks:
      - crypto-net 
      
  mysqldb:
      image: mysql:5.7
      environment:
        MYSQL_ROOT_PASSWORD: 123456
        # create database name crypto_db
        MYSQL_DATABASE: crypto_db
      networks:
      - crypto-net

networks:
  crypto-net:
    driver: bridge